[proton]
name = "Proton CachyOS"
variant = "proton-cachyos"
latest = "11.0-20260602"

[version."11.0-20260602"]
package = "11-0-20260602"

[version."11.0-20260602".download.x86_64-linux]
release = "cachyos-11.0-20260602-slr"
file = "proton-cachyos-11.0-20260602-slr-x86_64.tar.xz"
sha256 = "sha256-qC20cEi08yTC1RMu8mCXbrIf+yl1QBUpFSKzRKzmZTg="

[version."10.0-sunset"]
package = "10-0-sunset"

[version."10.0-sunset".download.x86_64-linux]
release = "cachyos-10.0-sunset-slr"
file = "proton-cachyos-10.0-sunset-slr-x86_64.tar.xz"
sha256 = "sha256-1uG6pmk37VjoVLIBPA7zs/H7xR174J40pa2jRC6pRS0="

[version."9.0-sunset"]
package = "9-0-sunset"

[version."9.0-sunset".download.x86_64-linux]
release = "cachyos-9.0-20250426-slr"
file = "proton-cachyos-9.0-20250426-slr-x86_64.tar.xz"
sha256 = "sha256-aARJfz4pjuc1U4F5QExPpBSuDOC7Ey4gM2W2TecZttM="
