# Configuration for treefmt.
#
# Program: https://treefmt.com/latest/
# ==============================================================================
excludes = [
  # IDE files
  ".idea",
  ".vscode",

  # system files
  ".DS_Store",
  "._*",

  # devenv
  ".devenv*",
  ".direnv",
  "devenv.local.nix",

  # tooling
  ".envrc",
  ".editorconfig",
  ".git*",
  "*.lock",

  # unsupported
  "__pycache__",
  "*.md",
]

[formatter.nixfmt]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.yq]
command = "yq"
options = ["--prettyPrint", "--indent=2"]
excludes = []
includes = ["*.json", "*.yaml", "*.yml"]

[formatter.tombi]
command = "tombi"
options = ["format"]
excludes = []
includes = ["*.toml"]

[formatter.shfmt]
command = "shfmt"
excludes = []
includes = ["*.sh", "*.bash"]
options = ["-w", "-i", "4"]

[formatter.ruff]
command = "ruff"
excludes = []
includes = ["*.py"]
options = ["format"]
