name: 'Rebase Branch'
description: 'Rebases a branch on top of another branch.'
inputs:

  head-branch:
    description: 'The branch to rebase.'
    required: true

  base-branch:
    description: 'The base branch.'
    required: true

  repo-dir:
    description: 'The repo directory.'
    required: false
    default: '.'

  fetch-depth:
    description: 'The number of commits to unshallow at a time'
    required: false
    default: '15'

runs:
  using: "composite"
  steps:

    - name: "Ensure head branch exists"
      id: create-branch
      shell: bash
      env:
        repo_dir: "${{ inputs.repo-dir }}"
        head_branch: "${{ inputs.head-branch }}"
        base_branch: "${{ inputs.base-branch }}"
      run: |-
        set -euo pipefail
        cd "${repo_dir}"
        git fetch

        # If the branch already exists, do nothing.
        if git rev-parse "refs/remotes/origin/${head_branch}" &>/dev/null; then
          printf "Branch '%s' already exists.\n" "${head_branch}"
          exit 0
        fi

        # If it doesn't, create it.
        git push origin "refs/remotes/origin/${base_branch}:refs/heads/${head_branch}"
        git fetch

    - name: "Find common ancestor"
      id: find-merge-base
      shell: bash
      env:
        repo_dir: "${{ inputs.repo-dir }}"
        head_branch: "${{ inputs.head-branch }}"
        base_branch: "${{ inputs.base-branch }}"
        fetch_depth: "${{ inputs.fetch-depth }}"
      run: |-
        set -euo pipefail
        cd "${repo_dir}"

        find_ancestor() {
          git merge-base \
            "refs/remotes/origin/${head_branch}" \
            "refs/remotes/origin/${base_branch}"
        }

        while true; do
          if [[ "$(git rev-parse --is-shallow-repository)" != "true" ]]; then
            printf "Could not find common ancestor between '%s' and '%s'\n" \
              "${head_branch}" "${base_branch}"
            exit 1
          fi

          if ancestor=$(find_ancestor); then
            printf "Found common ancestor: %s\n" "${ancestor}"
            printf "commit=${ancestor}\n" >>"$GITHUB_OUTPUT"
            exit 0
          fi

          git fetch --deepen="${fetch_depth}" origin
        done

    - name: "Rebase branch"
      shell: bash
      env:
        repo_dir: "${{ inputs.repo-dir }}"
        head_branch: "${{ inputs.head-branch }}"
        base_branch: "${{ inputs.base-branch }}"
      run: |-
        set -euo pipefail
        cd "${repo_dir}"

        # Go back to the current branch after performing the rebase.
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        cleanup() {
          git rebase --abort || true
          git checkout "$current_branch"
        }
        trap cleanup EXIT

        # Perform the rebase.
        git checkout "refs/remotes/origin/${head_branch}"
        git checkout -b "${head_branch}"
        git rebase "refs/remotes/origin/${base_branch}"
        git push origin HEAD:"refs/heads/${head_branch}" --force-with-lease
