{
  lib,
}:
let

  # The module option type for a protonfix.
  type = lib.types.submodule {
    options = {
      name = lib.mkOption {
        type = lib.types.str;
        description = "The application name.";
      };

      includeGlobalFixes = lib.mkOption {
        default = false;
        type = lib.types.bool;
        description = "Include the protonfixes bundled with the launched Proton version.";
      };

      alias = lib.mkOption {
        default = [ ];
        type = lib.types.either (lib.types.listOf lib.types.str) (lib.types.str);
        description = "Additional app IDs for this protonfix.";
      };

      environmentVariables = lib.mkOption {
        default = { };
        type = lib.types.attrsOf (lib.types.str);
        description = "App environment variables to override.";
      };

      extraFixes = lib.mkOption {
        default = "";
        type = lib.types.lines;
        description = "Extra Python code to run at the end of the protonfix.";
      };

      # TODO: Support more of https://github.com/Open-Wine-Components/umu-protonfixes/blob/master/util.py
    };
  };

  # Returns a list of aliases for the given protonfix module.
  aliasesOf = fix: if lib.isString fix.alias then [ fix.alias ] else fix.alias;

  # Generates the protonfix script.
  generateProtonfix =
    fix:
    let
      setEnvironmentVar =
        name: value: "util.set_environment(${escapePythonString name}, ${escapePythonString value})";

      pyImportGlobalFixFunc = ''
        def _include_global_fix():
            try:
                from protonfixes.fix import get_game_id, get_module_name
                from protonfixes.logger import log
                from importlib.util import find_spec
                from importlib import import_module

                is_default = __name__.endswith(".default")
                game_id = get_game_id()
                name = get_module_name(game_id, default=is_default, local=False)
                if find_spec(name) is None:
                    return

                mod = import_module(name)
                if mod is None or not hasattr(mod, "main"):
                    return

                log.info(f"Including global protonfix ({game_id}) [nix-proton]")
                mod.main()
            except Exception as e:
                log.warn("Error including global protonfix [nix-proton]")
                log.warn(str(e))
                return
      '';

      fixMainBody = lib.strings.trim ''
        ${lib.optionalString fix.includeGlobalFixes "_include_global_fix()"}
        ${lib.strings.concatMapAttrsStringSep "\n" setEnvironmentVar fix.environmentVariables}
        ${fix.extraFixes}
      '';
    in
    ''
      # Generated by home-manager (eth-p/nix-proton). DO NOT EDIT.
      ${escapePythonMultilineString fix.name}
      from protonfixes import util

      ${lib.optionalString fix.includeGlobalFixes pyImportGlobalFixFunc}

      def main() -> None:
      ${indentPython 4 (if fixMainBody == "" then "pass" else fixMainBody)}
    '';

  escapePythonString = s: ''"${lib.strings.replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ] s}"'';
  escapePythonMultilineString = s: ''"""${lib.strings.replaceString "\"\"\"" "\\\"\\\"\\\"" s}"""'';

  indentPython =
    spaces: s:
    let
      indent = lib.strings.concatStrings (lib.replicate spaces " ");
      lines = lib.strings.splitString "\n" s;
    in
    lib.strings.join "\n" (lib.lists.map (l: "${indent}${l}") lines);

in
{
  inherit type aliasesOf generateProtonfix;
}
