{
  lib,
}:
let

  # The module option type for a protonfix.
  type = lib.types.submodule {
    options = {
      name = lib.mkOption {
        type = lib.types.str;
        description = "The application name.";
      };

      alias = lib.mkOption {
        default = [ ];
        type = lib.types.either (lib.types.listOf lib.types.str) (lib.types.str);
        description = "Additional app IDs for this protonfix.";
      };

      environmentVariables = lib.mkOption {
        default = { };
        type = lib.types.attrsOf (lib.types.str);
        description = "App environment variables to override.";
      };

      extraFixes = lib.mkOption {
        default = "";
        type = lib.types.lines;
        description = "Extra Python code to run at the end of the protonfix.";
      };

      # TODO: Support more of https://github.com/Open-Wine-Components/umu-protonfixes/blob/master/util.py
    };
  };

  # Returns a list of aliases for the given protonfix module.
  aliasesOf = fix: if lib.isString fix.alias then [ fix.alias ] else fix.alias;

  # Generates the protonfix script.
  generateProtonfix =
    fix:
    let
      setEnvironmentVar =
        name: value: "util.set_environment(${escapePythonString name}, ${escapePythonString value})";

      fixMainBody = lib.strings.trim ''
        ${lib.strings.concatMapAttrsStringSep "\n" setEnvironmentVar fix.environmentVariables}
        ${fix.extraFixes}
      '';
    in
    ''
      # Generated by home-manager (eth-p/nix-protonfixes). DO NOT EDIT.
      ${escapePythonMultilineString fix.name}
      from protonfixes import util

      def main() -> None:
      ${if fixMainBody == "" then "    pass" else indentPython 4 fixMainBody}
    '';

  escapePythonString = s: ''"${lib.strings.replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ] s}"'';
  escapePythonMultilineString = s: ''"""${lib.strings.replaceString "\"\"\"" "\\\"\\\"\\\"" s}"""'';

  indentPython =
    spaces: s:
    let
      indent = lib.strings.concatStrings (lib.replicate spaces " ");
      lines = lib.strings.splitString "\n" s;
    in
    lib.strings.join "\n" (lib.lists.map (l: "${indent}${l}") lines);

in
{
  inherit type aliasesOf generateProtonfix;
}
